### ISSUE TITLE
LSTM de örneğinde features >750 deki hata

### ISSUE THREAD

**Issue by sametkaan** [erturkkadir/kurtahmini#2]
Kadir hocam merhaba; ben sizin LSTM örneğinizle 10 yıllık bir kur tahmin yapmak istiyorum. Fakat features değerini 750 den yukarı yazınca aşağıdaki hatalar oluşmaktadır. Bunun ilgili ne yapabilirim. 

output_size = 2         # sonraki 4 degeri tahmin etmeye calis
epochs =  1000   # islemi tekrar sayisi
features = 800

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-65-894bdc380ed4> in <module>
     71 model.fit(x_train, y_train, epochs=epochs, verbose=0)
     72 
---> 73 score = model.evaluate(x_test, y_test)
     74 print("%2s: %.2f%%" % (model.metrics_names[1], score[1]*100))
     75 model.summary()

~\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

~\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in evaluate(self, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, return_dict)
   1384               callbacks.on_test_batch_end(end_step, logs)
   1385       logs = tf_utils.to_numpy_or_python_type(logs)
-> 1386       callbacks.on_test_end(logs=logs)
   1387 
   1388       if return_dict:

~\Anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py in on_test_end(self, logs)
    546     for callback in self.callbacks:
    547       if getattr(callback, '_supports_tf_logs', False):
--> 548         callback.on_test_end(logs)
    549       else:
    550         if numpy_logs is None:  # Only convert once.

~\Anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py in on_test_end(self, logs)
    974   def on_test_end(self, logs=None):
    975     if not self._called_in_fit:
--> 976       self._finalize_progbar(logs)
    977 
    978   def on_predict_end(self, logs=None):

~\Anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py in _finalize_progbar(self, logs)
   1024       self.progbar.target = self.seen
   1025     logs = tf_utils.to_numpy_or_python_type(logs)
-> 1026     self.progbar.update(self.seen, list(logs.items()), finalize=True)
   1027 
   1028 

~\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py in update(self, current, values, finalize)
    579 
    580       if self.target is not None:
--> 581         numdigits = int(np.log10(self.target)) + 1
    582         bar = ('%' + str(numdigits) + 'd/%d [') % (current, self.target)
    583         prog = float(current) / self.target

OverflowError: cannot convert float infinity to integer

**Comment by erturkkadir** [comment]
Cok emin degilim ancak data hafizaya sigmiyor olabilir.

https://stackoverflow.com/questions/65525687/my-model-fit-and-model-evaluate-are-not-working-properly-and-i-am-getting-an-err

Tavsiyem once verilrinizi kontrol edin, aykiri deger (string vs) olmasin.
Ardindan  eger hafiza ekleyemiyorsaniz,  kolon sayisini dusurun.
