### ISSUE TITLE
LSTM'de başarı oranı %50 lerde

### ISSUE THREAD

**Issue by sametkaan** [erturkkadir/kurtahmini#3]
Hocam tekrardan merhaba;

Sizin  lstm örneğini kendim denediğimde sizin kodun aynısı ve aynı veri setini çalıştırdığımda bende %48  başarı oranı çıkıyor. Oysaki sizde %60 başarı oranı çıkmış. Yine aynı şekilde bendeki 3farklı para birimine ait verilerde de aynı şekilde %50-55 arası başarı oranı çıkıyor. Bir türlü %60-70 başarı oranı göremedim. Nerede hata yapıyor olabilirim. 

Jupyter notebook kullanıyorum. Tensorflow 2.3  yüklü

Teşekkürler.

Sizin verinizde aşağıdaki sonuç çıkmaktadır.

WARNING:tensorflow:5 out of the last 13 calls to <function Model.make_test_function.<locals>.test_function at 0x000002635C7261F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
3/3 [==============================] - 0s 4ms/step - loss: 0.0077 - accuracy: 0.4861
accuracy: 48.61%
Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_34 (LSTM)               (None, 1, 5)              180       
_________________________________________________________________
dropout_17 (Dropout)         (None, 1, 5)              0         
_________________________________________________________________
lstm_35 (LSTM)               (None, 7)                 364       
_________________________________________________________________
dense_17 (Dense)             (None, 2)                 16        
=================================================================
Total params: 560
Trainable params: 560
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000263568FEE50> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Gelecekteki Degerler (output_size) : [[4.22621685 4.22589708]]

**Comment by KadirErturk4r** [comment]
Ya library de yada kodlarda bir degisiklik olmali, 2 numarali hata tensor boylarinin farkli oldugunu soyluyor. 

Sonuclarin bu kadar fark etmesi beklenen birsey degil.
